# Generated by Django 3.1.5 on 2022-03-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePageApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_docdetails',
            name='uploadedTime',
            field=models.DateTimeField(),
        ),
    ]
