# Generated by Django 3.1.5 on 2022-03-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePageApp', '0002_auto_20220321_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_docdetails',
            name='uploadedTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
